name: Code Linting

steps:
  - uses: actions/checkout@v2

  - name: Install dependencies (linters)
    run: |
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Lint code
    run: |
      pycodestyle src tests
