name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Reference the separate YAML files
  lint:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/lint.yml

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting completes before testing
    uses: ./.github/workflows/unittests.yml
